# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FogFog-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FogFog-iOS
  pod 'GoogleMaps', '6.1.0'
  pod 'Google-Maps-iOS-Utils', '3.4.0'

  target 'FogFog-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FogFog-iOSUITests' do
    # Pods for testing
  end

end
